language: csharp
mono: latest

solution: Mononoke.sln
install:
  - nuget restore Mononoke.sln
  - nuget install NUnit.Console -Version 3.10.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release Mononoke.sln
  - echo 'FILES IN TEST FOLDER:'
  - ls ./MononokeEngine.Tests/bin/x86/Release/
  - mono ./testrunner/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe ./MononokeEngine.Tests/bin/x86/Release/MononokeEngine.Tests.dll