image: 
    - Visual Studio 2017
platform:
    - x86
configuration:
    - Release

test:
  # only assemblies to test
  assemblies:
    only:
      - MononokeEngine.Tests\bin\Debug\MononokeEngine.Tests.dll