version: AppVeyor {branch} Build {build}
image: Visual Studio 2015
 
branches:
    - master
    
platform: x86    
configuration: Release

build:
  project: Mononoke.sln
  verbosity: minimal

test:
  # only assemblies to test
  assemblies:
    - MononokeEngine.Tests\bin\Debug\MononokeEngine.Tests.dll