using MononokeEngine.Graphics.Core.Rendering;
using MononokeEngine.Graphics.Drawing;
using MononokeEngine.Scenes;

namespace MononokeEngine.Graphics.Core
{
    
    /// <summary>
    /// The GameRenderer takes all the commands generated by the
    /// <see cref="Draw"/> class
    /// and renders them on each <see cref="Scene"/>
    /// active <see cref="Camera"/>
    /// </summary>
    internal class GameRenderer
    {

        public void Render()
        {
            Scene scene = Mononoke.Scenes.Current;
            foreach (Camera cam in scene.Cameras)
                Render(cam);
        }

        public void CleanUp()
        {
            Scene scene = Mononoke.Scenes.Current;
            
            foreach (Layer layer in scene.Layers)
                layer.ClearDrawCommands();
        }

        private void Render(Camera cam)
        {
            Scene scene = Mononoke.Scenes.Current;
            
            foreach (Layer layer in scene.Layers)
            {
                IRenderer renderer = layer.Renderer;
                foreach (IDrawCommand cmd in layer.DrawCommands)
                {
                    if (!cmd.Accept(cam, renderer))
                        continue;
                    cmd.Execute(cam);
                }
            }
        }
        
    }
}